config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: {
    registrations: 'devise/registrations',
    sessions: 'devise/sessions',
  }

  resources :users,only: [:show,:index,:edit,:update] do
    get 'following_users' => 'relationships#following_users', as: 'following_users'
    get 'follower_users' => 'relationships#follower_users', as: 'follower_users'
    post 'follow' => 'relationships#follow', as: 'follow' # フォローする
    post 'unfollow' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  get '/search' => 'search#search'




end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save

    else
      @user = @book.user
      @book_new = Book.new
      render template "books/show"
    end
  end


  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.find(params[:id])
    @book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment.html.erb
<% book.book_comments.each do |comment| %>
<table>
  <td>
    <%= attachment_image_tag comment.user, :profile_image, :fill, 60, 60, fallback: 'no_image.jpg' %><br>
    <%= link_to comment.user.name, user_path(comment.user_id) %>
  </td>
  <td><%= comment.comment %></td>
  <% if comment.user_id == current_user.id %>
  <td><%= link_to 'Destroy', book_book_comment_path(comment.book,comment), method: :delete, remote: true %></td>
  <% end %>
</table>
<% end %>
<div class="comment_form">
  <%=form_with(model:[book, @book_comment], remote: true) do |f| %>
  <%= f.text_area :comment %>
  <%= f.submit '送信' %>
  <% end %>
</div>

app/views/book_comments/_comment_count.html.erb
コメント数：<%= @book.book_comments.count %>

app/views/book_comments/create.js.erb
$('#comment-index').html("<%= j (render 'book_comments/book_comment', book: @book) %>");
$('#comment-count').html("<%= j (render 'book_comments/comment_count', book: @book) %>");
$("textarea").val("");

app/views/book_comments/destroy.js.erb
$('#comment-index').html("<%= j (render 'book_comments/book_comment', book: @book) %>");
$('#comment-count').html("<%= j (render 'book_comments/comment_count', book: @book) %>");
$("textarea").val("");